---
apiVersion: v1
kind: Service
metadata:
  name: kafka-hs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: server
  - port: 7203
    name: jmx
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-cs
  labels:
    app: kafka
spec:
  ports:
  - port: 9092
    name: client
  - port: 7203
    name: jmx
  selector:
    app: kafka
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: kafka-pdb
spec:
  selector:
    matchLabels:
      app: kafka
  maxUnavailable: 1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  selector:
    matchLabels:
      app: kafka
  serviceName: kafka-hs
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        imagePullPolicy: IfNotPresent
        image: "ches/kafka"
        resources:
          requests:
            memory: "300Mi"
            cpu: "0.1"
        ports:
        - containerPort: 9092
          name: client
        - containerPort: 7203
          name: jmx
        env:
          - name: ZOOKEEPER_IP
            value: "zk-cs"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zk-cs:2181"